### ISSUE TITLE
Clinic doesn't work with Powershell

### ISSUE THREAD

**Issue by Arimanecro** [clinicjs/node-clinic#313] opened 2021-12-06 13:49 UTC
Hi.
I have a lot of deprications during npm installation:
https://i.imgur.com/c7UFe45.jpeg

Further...
`clinic doctor -- node server.js`
or
`clinic doctor --autocannon [ / ] -- node ./server.js`

And...nothing, screen:
https://i.imgur.com/700N9aQ.jpeg

P.S.
I use Node 17, Win10

**Comment by Arimanecro** [comment] 2021-12-06 15:14
> Check it with Node v16

That helped, thx

**Comment by sameer-coder** [comment] 2021-12-13 14:02
Couldn't reproduce the issue with node 17, win10, clinic@10.0.0

**Comment by ovhemert** [comment] 2021-12-14 08:57
@Arimanecro 
I'm able to reproduce the issue you have, but with slightly different results.

Win 10 / Node 16 / Clinic 10 / Command line => works!
Win 10 / Node 16 / Clinic 10 / Power shell => fails
Win 10 / Node 17 / Clinic 10 / Command line => works!
Win 10 / Node 17 / Clinic 10 / Power shell => fails

Can you verify if it also works for you running from Windows Command line (not Power shell) and Node v17?

**Comment by Arimanecro** [comment] 2021-12-14 11:25
@ovhemert 

> Win 10 / Node 17 / Clinic 10 / Command line => works!

Yeah, me too 👍

**Comment by ovhemert** [comment] 2021-12-14 12:31
@Arimanecro 
It seems to be an issue with PowerShell itself. 
Several resources on the web indicate this behaviour.

A double hyphen instructs PowerShell to treat everything coming after as literal arguments rather than options.
To avoid that behaviour you can either quote ("--", '--') or escape (`--) the double hyphen.

This works for me in PS:
`clinic doctor '--' node server.js`

cc @RafaelGSS : can you remove the "bug" label?.. maybe we can refer to this PS behaviour in the docs.

**Comment by RafaelGSS** [comment] 2021-12-14 12:50
Good catch!

**Comment by simoneb** [comment] 2021-12-31 14:08
Can we close this?

**Comment by RafaelGSS** [comment] 2021-12-31 14:56
I think that is doable to add a mention to not support powershell in the docs.

**Comment by simoneb** [comment] 2021-12-31 14:57
Let's do that then!

**Closed** 2022-01-07 19:52 UTC
Labels: good first issue, documentation
