### ISSUE TITLE
Does clinic.js works with Nextjs?

### ISSUE THREAD

**Issue by guimochila** [clinicjs/node-clinic#260] opened 2020-07-31 08:07 UTC
## Expected Behavior

I have a project that is in Nextjs and Typescript. As we really need SEO, SSR is a must. However the project seems to be really slow and we are trying to dig in what is the root causes of the issue and I just found out about Clinic.js which seems to be a good tool for this.

When running the command: `$ clinic doctor -- node dist/server/index.js` I would expected to get the report from Clinicjs.

## Current Behavior

Running the command: `$ clinic doctor -- node dist/server/index.js` ends with this result always:

```
`[=== ] Analysing dataundefined:1
[{"pid":94325,"tid":775,"ts":610333271714,"tts":142032,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tExecute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":94326,"tid":775,"ts":610333454873,"tts":153118,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":94326,"tid":775,"ts":610333454890,"tts":153135,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":94326,"tid":775,"ts":610333467923,"tts":153165,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":94326,"tid":775,"ts":610333468204,"tts":153446,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":94326,"tid":775,"ts":610333468213,"tts":153454,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":94326,"tid":775,"ts":610333468246,"tts":153488,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":94326,"tid":775,"ts":610333468402,"tt

SyntaxError: Unexpected token , in JSON at position 113
    at JSON.parse (<anonymous>)
    at Parser._transform (/Users/user/.config/yarn/global/node_modules/@nearform/trace-events-parser/index.js:41:34)
    at Parser.Transform._read (_stream_transform.js:191:10)
    at Parser.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Parser.Writable.write (_stream_writable.js:316:11)
    at TraceEventDecoder._transform (/Users/user/.config/yarn/global/node_modules/@nearform/doctor/format/trace-event-decoder.js:60:19)
    at TraceEventDecoder.Transform._read (_stream_transform.js:191:10)
    at TraceEventDecoder.Transform._write (_stream_transform.js:179:12)`
```

## Environment

* Clinic.js version: v5.0.3

* Node.js version: v12.16.1 npm v6.13.4

* Operating system and version: MacOS Darwin local 19.5.0 Darwin Kernel Version 19.5.0.

**Comment by fr-nevin** [comment] 2020-07-31 11:23
@guimochila Same! 
`^C[    ] Received Ctrl+C, closing process...
[  ==] Analysing dataundefined:1
[{"pid":41448,"tid":775,"ts":38101277220,"tts":869878,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":41448,"tid":775,"ts":38101287790,"tts":869897,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":41448,"tid":775,"ts":38101287866,"tts":869972,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":41448,"tid":775,"ts":38101287888,"tts":869985,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":41448,"tid":775,"ts":38101287903,"tts":870001,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":41448,"tid":775,"ts":38101287935,"tts":870016,"ph":"B","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{}},{"pid":41448,"tid":775,"ts":38101287943,"tts":870024,"ph":"E","cat":"v8","name":"V8.Execute","dur":0,"tdur":0,"args":{"runtime-call-stats":{}}},{"pid":41448,"tid":775,"ts":38101299602,"tts":870042,"ph":"B","cat":"v

SyntaxError: Unexpected token } in JSON at position 27791
    at JSON.parse (<anonymous>)
    at Parser._transform (/Users/01244861/.config/yarn/global/node_modules/@nearform/trace-events-parser/index.js:41:34)
    at Parser.Transform._read (_stream_transform.js:191:10)
    at Parser.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Parser.Writable.write (_stream_writable.js:316:11)
    at TraceEventDecoder._transform (/Users/01244861/.config/yarn/global/node_modules/@nearform/doctor/format/trace-event-decoder.js:60:19)
    at TraceEventDecoder.Transform._read (_stream_transform.js:191:10)
    at TraceEventDecoder.Transform._write (_stream_transform.js:179:12)`

**Comment by DylanC** [comment] 2020-09-09 09:53
@guimochila @fr-nevin - Does the information in #253 help?

**Comment by guimochila** [comment] 2020-09-09 10:11
@DylanC Unfortunately not as I'm already running clinic in a compiled version.  `$ clinic doctor -- node dist/server/index.js`, you can see that node runs on **dist/server** folder which is where the source is compiled. Thanks anyway. xD I guess the reason it is because as far as I know, clinic doesn't run on projects that spawn process described here #159.

**Comment by DylanC** [comment] 2020-09-09 14:16
@guimochila - Yes, that is correct! Child processes are not supported yet.

**Comment by afbarbaro** [comment] 2021-03-13 00:01
I found a _workaround_ for this when running next dev server.  It's not yet in nextjs but I plan to submit a pull request to their repo, then cross-link the PR/issue here.  

It turns out that next dev server uses Jest Worker and it has an option to run [worker threads](https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads).  If you enable that, then `clinic.js` works!

To get this working locally, you can patch this file in your next package under `node_modules`:
`node_modules/next/dist/server/next-dev-server.js`.  

Simply find the worker config:
`{maxRetries:0,numWorkers:this.nextConfig.experimental.cpus,forkOptions:{env: ...`

and change add `enableWorkerThreads:true`, for example:
`{enableWorkerThreads:true,maxRetries:0,numWorkers:this.nextConfig.experimental.cpus,forkOptions:{env: ...`

Also, if you're using in an older version of Node (<=10) you also will need to pass this flag to node: `--experimental-worker`.

Hope this helps you and also that next adds this as a supported configuration 🤞.

**Comment by fillon** [comment] 2021-06-09 23:59
Hi @afbarbaro 

After making the change in `next-dev-server.js`, how do you run `clinic` ?

`clinic doctor --on-port --autocannon [ -c 2 -d 5 / ] -- node ./node_modules/.bin/next dev    ???

**Comment by RafaelGSS** [comment] 2021-11-18 03:20
Hello guys! I couldn't reproduce it locally, if you are still experiencing that error, please create a reproducible code (preferable a repository) and share it here with your system info (node version, clinic version, OS)

**Comment by simoneb** [comment] 2021-12-01 23:34
@RafaelGSS did you try reproducing what the OP described with a ts next.js project? Also, if you confirm this issue is now fixed, you could check on Node 12 if it was there, suggesting that it would be the Node version which made a difference.

**Comment by RafaelGSS** [comment] 2021-12-02 13:27
> @RafaelGSS did you try reproducing what the OP described with a ts next.js project? Also, if you confirm this issue is now fixed, you could check on Node 12 if it was there, suggesting that it would be the Node version which made a difference.

I'll check it soon

**Comment by RafaelGSS** [comment] 2021-12-02 17:24
@simoneb just as feedback, I took a Next.js SSR Application as an example: https://github.com/daneden/next-ssr-example

```console
git clone git@github.com:daneden/next-ssr-example.git && cd next-ssr-example
yarn
yarn build
clinic doctor --autocannon [ / --method GET ] -- node ./node_modules/.bin/next start
```

and it works and all the versions tested (v12, v14, v16).

**Comment by RafaelGSS** [comment] 2021-12-02 18:21
Just to followup, I have tried to reproduce it using Typescript as well by just running:

```console
npx create-next-app@latest --ts
npm run build
clinic doctor --autocannon [ / --method GET ] -- node ./node_modules/.bin/next start
```

and it's working fine in all the node versions tested (v12, v14, v16). In that case, I'll close the issue.

**Closed by RafaelGSS** 2021-12-02 18:21 UTC

**Comment by zotijs** [comment] 2024-03-07 13:24
For anyone that ends up here trying to run `clinic doctor` in Next.js, this is what worked for me:

```
clinic doctor -- node ./node_modules/next/dist/bin/next start
```

with pnpm without installing `clinic` as global or dev dependency:

```
pnpm dlx clinic doctor -- node ./node_modules/next/dist/bin/next start
```
