### ISSUE TITLE
Node 14 read ECONNRESET error

### ISSUE THREAD

**Issue by aaestrada** [clinicjs/node-clinic#296] opened 2021-11-04 17:10 UTC
I'm running performance and capacity tests with [Clinic js](https://clinicjs.org/documentation/)

but when enable this `hapi-pino` library i receive the following error

`[1636045080852] INFO (23140 on MacBook-Pro-de-Aaron.local): request completed
    req: {
      "id": "1636045080846:MacBook-Pro-de-Aaron.local:23140:kvl6zrp4:12905",
      "method": "get",
      "url": "/items",
      "headers": {
        "host": "localhost:3000",
        "connection": "keep-alive"
      },
      "remoteAddress": "127.0.0.1",
      "remotePort": 56007
    }
    res: {
      "statusCode": 200,
      "headers": {
        "content-type": "application/json; charset=utf-8",
        "cache-control": "no-cache",
        "content-length": 96,
        "accept-ranges": "bytes"
      }
    }
    responseTime: 6
[1636045080853] ERROR (23140 on MacBook-Pro-de-Aaron.local):
    err: {
      "type": "Error",
      "message": "read ECONNRESET",
      "stack":
          Error: read ECONNRESET
              at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
              at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
      "errno": -54,
      "code": "ECONNRESET",
      "syscall": "read"
    }`
    
    i make public repo to reproduce this error.
    
   https://github.com/aaestrada/hapi-node-14-example
   
   There is old the information to test and reproduce this error.
   
let me know i there is something more than i can do!

**Comment by RafaelGSS** [comment] 2021-12-10 18:08
Thanks for pointing that out.

Would you like to create a PR? Remember to add test.

**Comment by ovhemert** [comment] 2021-12-13 08:01
This is a duplicate of the following issue: https://github.com/pinojs/hapi-pino/issues/145
PR already there for the fix in `hapi-pino`.

**Comment by simoneb** [comment] 2021-12-13 08:49
Thanks for catching this @ovhemert . Closing as duplicate.

**Closed by simoneb** 2021-12-13 08:49 UTC
Labels: confirmed bug
